# **Tensors**
**Tensors** are used to represent data in neural networks. Real world information are encoded into tensors for the computer and neural network to work on.

The main advantage of using tensors is their ability to make use of hardware acceleration provided by GPUs and TPUs that are able to perform large sets of calculations efficiently by allowing for parallel processing.

In [54]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Remember to include this line at the beginning of every .ipynb file to allow for the console to show all outputs from line evaluations and not just the last one
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"


After having imported all the necessary libraries, let's check for the version of PyTorch installed in the system.

In [ ]:
torch.__version__

## Creating Tensors

All the data stored an utilized in pytorch are stored as tensors. PyTorch tensors are created using **torch.tensor()**

Tensors are of several types and one of the classification is made on the basis of the rank of the tensor. They are:

*   Rank 0 Tensors (No basis vectors utilized -- **Scalars**)
*   Rank 1 Tensors (One basis vector for each direction -- **Vectors**)
*   Rank 2 Tensors (Two basis vector for each direction)
*   Rank 3 Tensors (Three basis vectors for each direction)

### Scalars

In [ ]:
# Creating scalars.
# Scalars are tensors of rank 0
SCALAR =  torch.tensor(7) # Returns a pytorch tensor with no "autograd history" --> look into autograd mechanics
torch.is_tensor(SCALAR) # Returns True if the passed object is a PyTorch tensor
SCALAR.ndim# Returns the number of dimensions of ndarray in python
SCALAR.shape# --> Look into it
SCALAR.item() # Returns the item in the scalar (tensor of rank 0) as a regular python integer

### Vectors

In [ ]:
# Vectors are created similar to scalars
VECTOR = torch.tensor([7,7])
VECTOR.ndim
VECTOR.shape

### Matrices

In [ ]:
# Matrices are created as
MATRIX = torch.tensor([[1,2], [3,4]])
MATRIX.ndim
MATRIX.shape
MATRIX[0]

### Tensors

In [ ]:
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]],[[28,29,30],[31,32,33],[34,35,36]]])
TENSOR.ndim
TENSOR.shape
TENSOR[1][2][1]

### Random Tensors

Random tensors are useful because neural networks usually start with a random collection of data and then tune them to better fit the problem's solution.
Manually initializing tensors that may contain thousands of data is impracical

In [ ]:
# Creating a random tensor of size (3,5,2)
random = torch.rand(5,3,4)
random[3][1][3].item()
random.ndim
random.shape
# Creating a tensor of shape similar to an image tensor
random_image = torch.rand(size = (244,244,3)) # Height, width and color channels
print(random_image.shape, random_image.ndim)

### Zeros and Ones

The .zeros() method creates a tensor of required shape made up entirely of zeros. Tensors with only zeros and ones are used as masks to separate certain region of interest in an image. The .ones() method does the same thing but for ones for all elements.

In [ ]:
ZEROS = torch.zeros(size = (5,10,10))
ONES = torch.ones(size = (5,3,4))
# print(ZEROS, ONES)

# Notes that T1 * T2  where T1 and T2 are tensors performs a simple correspondent element multiplication. So,
# print(random * ZEROS)

try:
  ONES*random
except RuntimeError:
  print("Mismatched Dimension") # AS the code clearly explains

### .dtype 

is the property of tensor that represents the type of data stored in the tensor

In [ ]:
ZEROS.dtype

### Range of tensors & tensor-like

.arange() returns a rank 2 tensor with elements ranging from start (inclusive) to end (exclusive) with steps (1 by default)

In [ ]:
range = torch.arange(start=0, end=78) # .arange() is left inclusive and right exclusive
range

.zeros_like() returns a tensor of shape same as that of input but with each element zero .ones_like() works in a similar way but for ones and .rand_like() for random values

In [ ]:
tens_zeroes_like = torch.rand_like(input=random)
tens_zeroes_like

### Tensor datatypes

Tensors in PyTorch by default store data in float_32 dtype unless explicitly initialized ie. .rand() .zeroes() and .ones() .rand_like() return a tensor of dtype float_32. The major error points while coding with PyTorch are:
*  selection of datatypes 
*  wrong tensor dimensions 
*  tensors not on the right device

While initializing tensors we can pass params like:
*  dtype: datatype of tensor (torch.floa32 / torch.float64)
*  device: which device is the tensor on or associated with GPU or CPU
*  requires_grad: if PyTorch should track the gradients of the tensor while it is computed on

In [65]:
float_32 = torch.tensor([3.0,6.0,9.0], dtype=None, device=None, requires_grad=False)
new = torch.rand_like(input=float_32, dtype=torch.float64)
new
float_32
float_32.dtype

tensor([0.0863, 0.3769, 0.7311], dtype=torch.float64)

tensor([3., 6., 9.])

torch.float32

### Typecasting

Explicit typecasting is donw by .type() method

In [66]:
float_16 = float_32.type(torch.float16)
float_16

tensor([3., 6., 9.], dtype=torch.float16)

Here we see that the result is implicitly typecasted to be float32

In [67]:
result = float_16 * float_32
result.dtype

torch.float32

Tensor attributes can be fetched as:
*  datatype: tensor.dtype
*  device: tensor.device
*  shape: tensor.shape | can also use tensor.size(). While shape is a property, size is a method

In [64]:
result.dtype
result.shape
result.device

torch.float32

torch.Size([3])

device(type='cpu')

In [ ]:
# .to() method can change the tensor attributes like device and dtype
# result.to(device="cuda", dtype=torch.float64)