# **Tensors**
**Tensors** are used to represent data in neural networks. Real world information are encoded into tensors for the computer and neural network to work on.

The main advantage of using tensors is their ability to make use of hardware acceleration provided by GPUs and TPUs that are able to perform large sets of calculations efficiently by allowing for parallel processing.

In [1]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Remember to include this line at the beginning of every .ipynb file to allow for the console to show all outputs from line evaluations and not just the last one
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"


After having imported all the necessary libraries, let's check for the version of PyTorch installed in the system.

In [2]:
torch.__version__

'2.1.0+cpu'

## Creating Tensors

All the data stored an utilized in pytorch are stored as tensors. PyTorch tensors are created using **torch.tensor()**

Tensors are of several types and one of the classification is made on the basis of the rank of the tensor. They are:

*   Rank 0 Tensors (No basis vectors utilized -- **Scalars**)
*   Rank 1 Tensors (One basis vector for each direction -- **Vectors**)
*   Rank 2 Tensors (Two basis vector for each direction)
*   Rank 3 Tensors (Three basis vectors for each direction)

### Scalars

In [3]:
# Creating scalars.
# Scalars are tensors of rank 0
SCALAR =  torch.tensor(7) # Returns a pytorch tensor with no "autograd history" --> look into autograd mechanics
torch.is_tensor(SCALAR) # Returns True if the passed object is a PyTorch tensor
SCALAR.ndim# Returns the number of dimensions of ndarray in python
SCALAR.shape# --> Look into it
SCALAR.item() # Returns the item in the scalar (tensor of rank 0) as a regular python integer

True

0

torch.Size([])

7

### Vectors

In [4]:
# Vectors are created similar to scalars
VECTOR = torch.tensor([7,7])
VECTOR.ndim
VECTOR.shape

1

torch.Size([2])

### Matrices

In [5]:
# Matrices are created as
MATRIX = torch.tensor([[1,2,3], [3,4,5]])
MATRIX.ndim
MATRIX.shape
MATRIX[0]

2

torch.Size([2, 3])

tensor([1, 2, 3])

### Tensors

In [6]:
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]],[[28,29,30],[31,32,33],[34,35,36]]])
TENSOR.ndim
TENSOR.shape
TENSOR[1][2][1]

3

torch.Size([4, 3, 3])

tensor(17)

### Random Tensors

Random tensors are useful because neural networks usually start with a random collection of data and then tune them to better fit the problem's solution.
Manually initializing tensors that may contain thousands of data is impracical

In [7]:
# Creating a random tensor of size (3,5,2)
random = torch.rand(5,3,4)
random[3][1][3].item()
random.ndim
random.shape
# Creating a tensor of shape similar to an image tensor
random_image = torch.rand(size = (244,244,3)) # Height, width and color channels
print(random_image.shape, random_image.ndim)

0.8096449375152588

3

torch.Size([5, 3, 4])

torch.Size([244, 244, 3]) 3


### Zeros and Ones

The .zeros() method creates a tensor of required shape made up entirely of zeros. Tensors with only zeros and ones are used as masks to separate certain region of interest in an image. The .ones() method does the same thing but for ones for all elements.

In [8]:
ZEROS = torch.zeros(size = (5,10,10))
ONES = torch.ones(size = (5,3,4))
# print(ZEROS, ONES)

# Notes that T1 * T2  where T1 and T2 are tensors performs a simple correspondent element multiplication. So,
# print(random * ZEROS)

try:
  ONES*random
except RuntimeError:
  print("Mismatched Dimension") # AS the code clearly explains

tensor([[[0.2533, 0.7509, 0.6889, 0.7865],
         [0.0781, 0.0205, 0.2775, 0.1386],
         [0.3088, 0.1632, 0.2850, 0.0092]],

        [[0.9773, 0.0982, 0.5991, 0.8747],
         [0.8261, 0.9895, 0.9997, 0.7573],
         [0.3277, 0.9900, 0.0505, 0.9763]],

        [[0.8863, 0.9388, 0.5372, 0.6590],
         [0.0835, 0.6303, 0.8548, 0.4604],
         [0.6788, 0.8651, 0.8510, 0.1125]],

        [[0.5056, 0.6784, 0.0389, 0.9878],
         [0.8916, 0.1350, 0.6975, 0.8096],
         [0.4436, 0.5329, 0.3209, 0.6579]],

        [[0.7794, 0.9716, 0.8875, 0.4596],
         [0.5941, 0.0899, 0.4820, 0.7920],
         [0.8830, 0.7576, 0.3215, 0.6881]]])

In [9]:
ZEROS.dtype

torch.float32

### Range of tensors & tensor-like

.arange() returns a rank 2 tensor with elements ranging from start (inclusive) to end (exclusive) with steps (1 by default)

In [10]:
range = torch.arange(start=0, end=78) # .arange() is left inclusive and right exclusive
range

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
        54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
        72, 73, 74, 75, 76, 77])

.zeros_like() returns a tensor of shape same as that of input but with each element zero .ones_like() works in a similar way but for ones and .rand_like() for random values

In [11]:
tens_zeroes_like = torch.rand_like(input=random)
tens_zeroes_like

tensor([[[0.3183, 0.7554, 0.6279, 0.2159],
         [0.9554, 0.0679, 0.1369, 0.9163],
         [0.5347, 0.9655, 0.3047, 0.7085]],

        [[0.0863, 0.9957, 0.2178, 0.3500],
         [0.2880, 0.6906, 0.4979, 0.1801],
         [0.1003, 0.3845, 0.6758, 0.8629]],

        [[0.7604, 0.2215, 0.8609, 0.1368],
         [0.3611, 0.4527, 0.6873, 0.4366],
         [0.8313, 0.6563, 0.1435, 0.2103]],

        [[0.0618, 0.5039, 0.8132, 0.8204],
         [0.1508, 0.8073, 0.9534, 0.3068],
         [0.1770, 0.5751, 0.9408, 0.5374]],

        [[0.2205, 0.4691, 0.0060, 0.3470],
         [0.2653, 0.5002, 0.5145, 0.7933],
         [0.8162, 0.1012, 0.5747, 0.5635]]])

## Tensor datatypes

Tensors in PyTorch by default store data in float_32 dtype unless explicitly initialized ie. .rand(), .zeroes(), .ones(), and .rand_like() return a tensor of dtype float_32. The major error points while coding with PyTorch are:
*  selection of datatypes 
*  wrong tensor dimensions 
*  tensors not on the right device

While initializing tensors we can pass params like:
*  dtype: datatype of tensor (torch.floa32 / torch.float64)
*  device: which device is the tensor on or associated with GPU or CPU
*  requires_grad: if PyTorch should track the gradients of the tensor while it is computed on

In [12]:
float_32 = torch.tensor([3.0,6.0,9.0], dtype=None, device=None, requires_grad=False)
new = torch.rand_like(input=float_32, dtype=torch.float64)
new
float_32
float_32.dtype

tensor([0.9210, 0.6168, 0.3775], dtype=torch.float64)

tensor([3., 6., 9.])

torch.float32

### .dtype 

is the property of tensor that represents the type of data stored in the tensor

### Typecasting

Explicit typecasting is done by .type() method

In [13]:
float_16 = float_32.type(torch.float16)
float_16.dtype

torch.float16

Here we see that the result is implicitly typecasted to be float32

> Note that the .type() method returns the typecasted tensor and so the returned tensor has to be assigned to some other new tensor or the original tensor

In [14]:
result = float_16 * float_32
result.dtype

torch.float32

Tensor attributes can be fetched as:
*  datatype: tensor.dtype
*  device: tensor.device
*  shape: tensor.shape | can also use tensor.size(). While shape is a property, size is a method

In [15]:
result.dtype
result.shape
result.size()
result.device

torch.float32

torch.Size([3])

torch.Size([3])

device(type='cpu')

.to() method can change the tensor attributes like device and dtype

In [16]:
# result.to(device="cuda", dtype=torch.float64)

## Tensor Manipulation

Tensors can be operated on as:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [17]:
test = torch.tensor([[[1,2,3],[4,5,6]]], dtype=torch.long)

# Addition
test + 7

# Multiplication
new_test = test * 4

# Subtraction
test - 12

# Division
test / 5

tensor([[[ 8,  9, 10],
         [11, 12, 13]]])

tensor([[[-11, -10,  -9],
         [ -8,  -7,  -6]]])

tensor([[[0.2000, 0.4000, 0.6000],
         [0.8000, 1.0000, 1.2000]]])

Tensors are multiplied in two ways:

* Multiplication with a scalar (*)
* Matrix Multiplication (@)


In [18]:
# Scalar multiplication
print(f"{test} * {new_test} = {test * new_test}")

# Matrix multiplication
# torch.matmul(test, new_test)

d1 = torch.tensor([[1,2,3],[4,5,6]])
d2 = torch.tensor([[1,2],[3,4]])
try:
  torch.matmul(d1,d2)
except Exception as exp:
  print(exp)

tensor([[[1, 2, 3],
         [4, 5, 6]]]) * tensor([[[ 4,  8, 12],
         [16, 20, 24]]]) = tensor([[[  4,  16,  36],
         [ 64, 100, 144]]])
mat1 and mat2 shapes cannot be multiplied (2x3 and 2x2)


One of the most frequent errors faced while working with neural networks and writing deep learning code is the size mismatch of tensors that are being multiplied. 

The two important rules followed are:

1. The inner dimensions must match:
  * `(3,2) @ (2,3)` will work
  * `(3,2) @ (3,2)` won't work
  * `(2,3) @ (3,2)` will work
  
2. The resulting matrix will have the shape of outer dimensions

>Note: inner dimensions for (5,7) and (4,6) are (5,4) and outer dimensions are (7,6)

## Tensor Aggregation

We can find the max, min, sum, avg of a tensor by using tensor aggregation methods.

In [19]:
random_tensor = torch.rand([3,3,3]) * 100
random_tensor = random_tensor.type(torch.int16) # Refer to the note in explicit typecasting section
random_tensor
random_tensor.dtype

tensor([[[50, 91, 59],
         [74, 28,  9],
         [69, 14, 94]],

        [[54, 99, 54],
         [ 6, 95, 37],
         [80, 50, 19]],

        [[43, 56, 97],
         [77,  8, 65],
         [ 8, 87,  9]]], dtype=torch.int16)

torch.int16

In [20]:
# Finding min
random_tensor.min()

# Finding max
random_tensor.max()

# Finding mean
try:
  random_tensor.mean()
except RuntimeError:
  print("Tensor must be of dtype float or complex and not integer")

# Finding sum
random_tensor.sum()

# Finding the positional min
random_tensor.argmin()

# Finding the positional max
random_tensor.argmax()

tensor(6, dtype=torch.int16)

tensor(99, dtype=torch.int16)

Tensor must be of dtype float or complex and not integer


tensor(1432)

tensor(12)

tensor(10)

> Note that the .argmin() and .argmax() methods return the position of the min and max value assuming that the tensor is one dimensional ie. In a 3x3x3 tensor if the element of index `[1][2][1]` is min then the value returned by the method will be 16. We can see that the reasoning behind the result is that position is counted as 8 when we reach `[0][2][2]` from `[0][0][0]` and continue as 9 for `[1][0][0]`

## Reshaping, Stacking, Squeezing, and Unsqueezing Tensors

* Reshape: reshape an input tensor to a desired shape
* View: return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking: stack multiple tensors on top of one another (**vstack**) or side-by-side (**hstack**)
* Squeeze: removes all `1` dimensions from a tensor
* Unsqueeze: adds a `1` dimension to a traget tensor
* Permute: return a view of the input tensor with its dimension permuted (**swapped**) in a certain way

In [37]:
tensor_new = torch.arange(1.0,49.0)
tensor_new

# Reshaping a tensor
try:
  reshaped_tensor = tensor_new.reshape([3,4,4])
except Exception as err:
  print(str(err) + "Total elements: 48 N 50 O")
  try:
    reshaped_tensor = tensor_new.reshape([4,13])
  except Exception as err:
      print(str(err) + "Total elements: 52 N 50 O")
      reshaped_tensor = tensor_new.reshape([5,5,2])
      reshaped_tensor
# reshaped_tensor = tensor_new.reshape([5,2,5])
# reshaped_tensor


tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
        15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26., 27., 28.,
        29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39., 40., 41., 42.,
        43., 44., 45., 46., 47., 48.])

> A key concept to note is that the .reshape() method can only reshape tensors into new tensors that are equivalent to the original ie the number of elements in them must be equal. We cannot exclude some elements from the new tensor nor can we create a tensor with empty positions.

In [67]:
# Changing the view of a tensor 
view_tensor = tensor_new.view(3,2,4,1,2)
view_tensor

tensor([[[[[ 1.,  2.]],

          [[ 3.,  4.]],

          [[ 5.,  6.]],

          [[ 7.,  8.]]],


         [[[ 9., 10.]],

          [[11., 12.]],

          [[13., 14.]],

          [[15., 16.]]]],



        [[[[17., 18.]],

          [[19., 20.]],

          [[21., 22.]],

          [[23., 24.]]],


         [[[25., 26.]],

          [[27., 28.]],

          [[29., 30.]],

          [[31., 32.]]]],



        [[[[33., 34.]],

          [[35., 36.]],

          [[37., 38.]],

          [[39., 40.]]],


         [[[41., 42.]],

          [[43., 44.]],

          [[45., 46.]],

          [[47., 48.]]]]])

One thing to note about the .view() method is that the tensor returned by it will share the same memory as the original tensor but the shape wiil be changed. Essentially, the changes made to the tensor returend will be reflected to the original tensor.

In [39]:
# Manipulating the view_tensor
view_tensor *= 10.0
tensor_new
tensor_new /= 10.0
view_tensor

tensor([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100., 110., 120.,
        130., 140., 150., 160., 170., 180., 190., 200., 210., 220., 230., 240.,
        250., 260., 270., 280., 290., 300., 310., 320., 330., 340., 350., 360.,
        370., 380., 390., 400., 410., 420., 430., 440., 450., 460., 470., 480.])

tensor([[[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.],
         [13., 14.],
         [15., 16.]],

        [[17., 18.],
         [19., 20.],
         [21., 22.],
         [23., 24.]],

        [[25., 26.],
         [27., 28.],
         [29., 30.],
         [31., 32.]],

        [[33., 34.],
         [35., 36.],
         [37., 38.],
         [39., 40.]],

        [[41., 42.],
         [43., 44.],
         [45., 46.],
         [47., 48.]]])

We see that the chages were applied to both view_tensor and tensor_new

In [ ]:
# Stacking tensors
stacked_tensor = torch.stack([view_tensor, view_tensor, view_tensor], dim=4)
view_tensor
stacked_tensor
view_tensor.shape
stacked_tensor.shape

The .stack() method stacks tensors. It takes two arguments, a tensor list and `dim`. While the list is self explanatory one may find it hard to grasp what dim does. The dim argument specifies the index of dimension that will be added to the stacked tensor ie. for `dim = 0` the tensors wll be stacked one after other. say three tensors of dimension `[2,3]` were stacked so the dimension of the new tensor will be `[3,2,3]`. The same tensor will have dimension `[2,3,3]` for `dim = 2`.
> Play around in the code block above to better understand it.


In [68]:
# Squeezing tensors
squeezed_tensor = view_tensor.squeeze()
squeezed_tensor
squeezed_tensor.shape

tensor([[[[ 1.,  2.],
          [ 3.,  4.],
          [ 5.,  6.],
          [ 7.,  8.]],

         [[ 9., 10.],
          [11., 12.],
          [13., 14.],
          [15., 16.]]],


        [[[17., 18.],
          [19., 20.],
          [21., 22.],
          [23., 24.]],

         [[25., 26.],
          [27., 28.],
          [29., 30.],
          [31., 32.]]],


        [[[33., 34.],
          [35., 36.],
          [37., 38.],
          [39., 40.]],

         [[41., 42.],
          [43., 44.],
          [45., 46.],
          [47., 48.]]]])

torch.Size([3, 2, 4, 2])

In [74]:
# Unsqueezing tensors
unsqueezed_tensor = squeezed_tensor.unsqueeze(1)
squeezed_tensor
unsqueezed_tensor
squeezed_tensor.shape
unsqueezed_tensor.shape

tensor([[[[ 1.,  2.],
          [ 3.,  4.],
          [ 5.,  6.],
          [ 7.,  8.]],

         [[ 9., 10.],
          [11., 12.],
          [13., 14.],
          [15., 16.]]],


        [[[17., 18.],
          [19., 20.],
          [21., 22.],
          [23., 24.]],

         [[25., 26.],
          [27., 28.],
          [29., 30.],
          [31., 32.]]],


        [[[33., 34.],
          [35., 36.],
          [37., 38.],
          [39., 40.]],

         [[41., 42.],
          [43., 44.],
          [45., 46.],
          [47., 48.]]]])

tensor([[[[[ 1.,  2.],
           [ 3.,  4.],
           [ 5.,  6.],
           [ 7.,  8.]],

          [[ 9., 10.],
           [11., 12.],
           [13., 14.],
           [15., 16.]]]],



        [[[[17., 18.],
           [19., 20.],
           [21., 22.],
           [23., 24.]],

          [[25., 26.],
           [27., 28.],
           [29., 30.],
           [31., 32.]]]],



        [[[[33., 34.],
           [35., 36.],
           [37., 38.],
           [39., 40.]],

          [[41., 42.],
           [43., 44.],
           [45., 46.],
           [47., 48.]]]]])

torch.Size([3, 2, 4, 2])

torch.Size([3, 1, 2, 4, 2])

In [77]:
# Permuting tensors
permuted_tensor = torch.permute(squeezed_tensor, (1,3,2,0))
permuted_tensor
permuted_tensor.shape

# Demonstrating that the permute method returns tensor in similar manner to view.
squeezed_tensor *= 10
permuted_tensor

tensor([[[[ 1., 17., 33.],
          [ 3., 19., 35.],
          [ 5., 21., 37.],
          [ 7., 23., 39.]],

         [[ 2., 18., 34.],
          [ 4., 20., 36.],
          [ 6., 22., 38.],
          [ 8., 24., 40.]]],


        [[[ 9., 25., 41.],
          [11., 27., 43.],
          [13., 29., 45.],
          [15., 31., 47.]],

         [[10., 26., 42.],
          [12., 28., 44.],
          [14., 30., 46.],
          [16., 32., 48.]]]])

torch.Size([2, 2, 4, 3])

tensor([[[[ 10., 170., 330.],
          [ 30., 190., 350.],
          [ 50., 210., 370.],
          [ 70., 230., 390.]],

         [[ 20., 180., 340.],
          [ 40., 200., 360.],
          [ 60., 220., 380.],
          [ 80., 240., 400.]]],


        [[[ 90., 250., 410.],
          [110., 270., 430.],
          [130., 290., 450.],
          [150., 310., 470.]],

         [[100., 260., 420.],
          [120., 280., 440.],
          [140., 300., 460.],
          [160., 320., 480.]]]])

The permute method reorganizes the input tensor in a specific order. To specify the order a tuple of the same length as the size tuple is to be passed where the index of the original size tuple are entered. Example: A tensor of size `(3,4,5,8)` is passed to `.permute(tensor, (2,3,0,1))`, the resulting tensor will have a size of `(5,8,3,4)`

## Indexing

Indexing with PyTorch is similar to indexing with NumPy

In [80]:

tensor_test = torch.arange(1,10).reshape([1,3,3])
tensor_test

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [92]:
# Accesing [0] th element of tensor
tensor_test[0]
# We get the same tensor as the dimension of tensor_test is [1,3,3]
# Accessing the 2nd element of 1st row 
tensor_test[0][0][1]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

tensor(2)

In [98]:
# Using : for indexing
# : selects all the elements in a dimension or ing general a list
tensor_test[0,:,1]

tensor([2, 5, 8])

- `tensor_test[0,:,1]` - This will select all elements from the second dimension (columns) of the first dimension (rows) at index 1 of the tensor. In other words, it’s selecting the second column from all rows of the first matrix in the tensor.

- `tensor_test[0][:][1]` - This is a chained indexing operation. The first indexing operation tensor_test[0] selects the first matrix in the tensor. The second indexing operation [:] selects all elements of this matrix. The third indexing operation [1] then selects the second element of the result. In this case, it will select the second row of the first matrix in the tensor.

> So, the difference between tensor_test[0,:,1] and tensor_test[0][:][1] is that the former selects a column from a matrix in the tensor, while the latter selects a row from a matrix in the tensor.

To fetch `3,6,9` from the tensor

In [99]:
tensor_test[0,:,2]

tensor([3, 6, 9])

## PyTorch and Numpy

Numpy being a widely used numerical computation library has been integrated i Pyorch to allow for better array and tensor manipulation. We can interchange betwee a Numpy ndarray and a pytorch tensor as follows:

- Pytorch -> Numpy: use `torch.Tensor.numpy()`
- Numpy -> pytorch: use `torch.from_numpy(ndarray)`

In [131]:
array = np.arange(1.0,9.0)
to_tensor = torch.from_numpy(array)
array, to_tensor, id(array), id(to_tensor)

(array([1., 2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64),
 1594465322544,
 1594465336016)

> Note that the `.from_numpy()` method reflects the default dtype of float64 of numpy while PyTorch has a default dtype of float32. Also the tensor thus formeed will not refer to the same memory location and a new variable is being created upon calling it.

In [132]:
id(array), id(to_tensor)
array = array * 2
id(array), id(to_tensor)
to_tensor


(1594465322544, 1594465336016)

(1594465328208, 1594465336016)

tensor([1., 2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64)

> Note that manipulating variables using `a += 1` and `a = a + 1` are different. The former changes the value in-place while the latter changes the value and creates a new memory instance of it. This is why if the array was manipulated using `+=` the tensor referring to its memory was also changed while using `a = a + n` results in the array changing but the tensor remaining the same.

In [134]:
# Changing from tensor to numpy
tensor = torch.ones([7,3])
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=float32))

## Reproducibility

The ability to recreate results when a program runs for multiple instances is `reporducibility`. The ability to reproduce an outcome is in direct contrast to the ability to work with random initial conditions. 

Sometimes you want the program to behave in the same way even though it is meant to work with randomly generated values later on. For this, instead of changing the program for debugging and for applicaton we can `seed` the `RNG` such that the random number generator will always produce the same set of values for all program executions.

In [136]:
torch.manual_seed(32)
random_tensor_one = torch.rand([3,4,5])
torch.manual_seed(32)
random_tensor_two = torch.rand([3,4,5])
random_tensor_one
random_tensor_two
random_tensor_one == random_tensor_two

tensor([[[0.8757, 0.2721, 0.4141, 0.7857, 0.1130],
         [0.5793, 0.6481, 0.0229, 0.5874, 0.3254],
         [0.9485, 0.5219, 0.8782, 0.7254, 0.6929],
         [0.0259, 0.9319, 0.0913, 0.7177, 0.7271]],

        [[0.4967, 0.9308, 0.3677, 0.2049, 0.6646],
         [0.3886, 0.0787, 0.1447, 0.1809, 0.6440],
         [0.1504, 0.7280, 0.8867, 0.2971, 0.7828],
         [0.5105, 0.8187, 0.4370, 0.1878, 0.8781]],

        [[0.1925, 0.6161, 0.7849, 0.1381, 0.0455],
         [0.7794, 0.0059, 0.1268, 0.7167, 0.3324],
         [0.8529, 0.3920, 0.5805, 0.2238, 0.5989],
         [0.0382, 0.1198, 0.1159, 0.5589, 0.4112]]])

tensor([[[0.8757, 0.2721, 0.4141, 0.7857, 0.1130],
         [0.5793, 0.6481, 0.0229, 0.5874, 0.3254],
         [0.9485, 0.5219, 0.8782, 0.7254, 0.6929],
         [0.0259, 0.9319, 0.0913, 0.7177, 0.7271]],

        [[0.4967, 0.9308, 0.3677, 0.2049, 0.6646],
         [0.3886, 0.0787, 0.1447, 0.1809, 0.6440],
         [0.1504, 0.7280, 0.8867, 0.2971, 0.7828],
         [0.5105, 0.8187, 0.4370, 0.1878, 0.8781]],

        [[0.1925, 0.6161, 0.7849, 0.1381, 0.0455],
         [0.7794, 0.0059, 0.1268, 0.7167, 0.3324],
         [0.8529, 0.3920, 0.5805, 0.2238, 0.5989],
         [0.0382, 0.1198, 0.1159, 0.5589, 0.4112]]])

tensor([[[True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True]],

        [[True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True]],

        [[True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True]]])