# **Tensors**
**Tensors** are used to represent data in neural networks. Real world information are encoded into tensors for the computer and neural network to work on.

The main advantage of using tensors is their ability to make use of hardware acceleration provided by GPUs and TPUs that are able to perform large sets of calculations efficiently by allowing for parallel processing.

In [1]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Remember to include this line at the beginning of every .ipynb file to allow for the console to show all outputs from line evaluations and not just the last one
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"


After having imported all the necessary libraries, let's check for the version of PyTorch installed in the system.

In [2]:
torch.__version__

'2.1.0+cpu'

## Creating Tensors

All the data stored an utilized in pytorch are stored as tensors. PyTorch tensors are created using **torch.tensor()**

Tensors are of several types and one of the classification is made on the basis of the rank of the tensor. They are:

*   Rank 0 Tensors (No basis vectors utilized -- **Scalars**)
*   Rank 1 Tensors (One basis vector for each direction -- **Vectors**)
*   Rank 2 Tensors (Two basis vector for each direction)
*   Rank 3 Tensors (Three basis vectors for each direction)

### Scalars

In [3]:
# Creating scalars.
# Scalars are tensors of rank 0
SCALAR =  torch.tensor(7) # Returns a pytorch tensor with no "autograd history" --> look into autograd mechanics
torch.is_tensor(SCALAR) # Returns True if the passed object is a PyTorch tensor
SCALAR.ndim# Returns the number of dimensions of ndarray in python
SCALAR.shape# --> Look into it
SCALAR.item() # Returns the item in the scalar (tensor of rank 0) as a regular python integer

True

0

torch.Size([])

7

### Vectors

In [4]:
# Vectors are created similar to scalars
VECTOR = torch.tensor([7,7])
VECTOR.ndim
VECTOR.shape

1

torch.Size([2])

### Matrices

In [5]:
# Matrices are created as
MATRIX = torch.tensor([[1,2,3], [3,4,5]])
MATRIX.ndim
MATRIX.shape
MATRIX[0]

2

torch.Size([2, 3])

tensor([1, 2, 3])

### Tensors

In [6]:
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]],[[28,29,30],[31,32,33],[34,35,36]]])
TENSOR.ndim
TENSOR.shape
TENSOR[1][2][1]

3

torch.Size([4, 3, 3])

tensor(17)

### Random Tensors

Random tensors are useful because neural networks usually start with a random collection of data and then tune them to better fit the problem's solution.
Manually initializing tensors that may contain thousands of data is impracical

In [7]:
# Creating a random tensor of size (3,5,2)
random = torch.rand(5,3,4)
random[3][1][3].item()
random.ndim
random.shape
# Creating a tensor of shape similar to an image tensor
random_image = torch.rand(size = (244,244,3)) # Height, width and color channels
print(random_image.shape, random_image.ndim)

0.8562103509902954

3

torch.Size([5, 3, 4])

torch.Size([244, 244, 3]) 3


### Zeros and Ones

The .zeros() method creates a tensor of required shape made up entirely of zeros. Tensors with only zeros and ones are used as masks to separate certain region of interest in an image. The .ones() method does the same thing but for ones for all elements.

In [8]:
ZEROS = torch.zeros(size = (5,10,10))
ONES = torch.ones(size = (5,3,4))
# print(ZEROS, ONES)

# Notes that T1 * T2  where T1 and T2 are tensors performs a simple correspondent element multiplication. So,
# print(random * ZEROS)

try:
  ONES*random
except RuntimeError:
  print("Mismatched Dimension") # AS the code clearly explains

tensor([[[0.3840, 0.9358, 0.4426, 0.4570],
         [0.0120, 0.4297, 0.1219, 0.1362],
         [0.2816, 0.9538, 0.2088, 0.0590]],

        [[0.0042, 0.1471, 0.3352, 0.2698],
         [0.9836, 0.0422, 0.7818, 0.9975],
         [0.4931, 0.7928, 0.6911, 0.0639]],

        [[0.2175, 0.1050, 0.3480, 0.8306],
         [0.8441, 0.1273, 0.6889, 0.6670],
         [0.2033, 0.3733, 0.5263, 0.4665]],

        [[0.4465, 0.3108, 0.3591, 0.0025],
         [0.2322, 0.6358, 0.4328, 0.8562],
         [0.3317, 0.8527, 0.7063, 0.2345]],

        [[0.0767, 0.9674, 0.5421, 0.2370],
         [0.4688, 0.4940, 0.0684, 0.0550],
         [0.5761, 0.2893, 0.9048, 0.4618]]])

In [9]:
ZEROS.dtype

torch.float32

### Range of tensors & tensor-like

.arange() returns a rank 2 tensor with elements ranging from start (inclusive) to end (exclusive) with steps (1 by default)

In [10]:
range = torch.arange(start=0, end=78) # .arange() is left inclusive and right exclusive
range

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
        54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
        72, 73, 74, 75, 76, 77])

.zeros_like() returns a tensor of shape same as that of input but with each element zero .ones_like() works in a similar way but for ones and .rand_like() for random values

In [11]:
tens_zeroes_like = torch.rand_like(input=random)
tens_zeroes_like

tensor([[[0.1682, 0.9584, 0.5182, 0.8582],
         [0.1351, 0.7625, 0.8064, 0.3467],
         [0.8004, 0.9544, 0.8159, 0.9838]],

        [[0.9247, 0.9132, 0.5023, 0.0025],
         [0.1865, 0.2317, 0.4969, 0.7124],
         [0.2173, 0.3090, 0.5018, 0.9604]],

        [[0.8642, 0.3839, 0.7381, 0.1736],
         [0.0307, 0.3168, 0.0526, 0.9932],
         [0.7912, 0.8032, 0.4988, 0.1782]],

        [[0.8176, 0.6464, 0.2367, 0.0263],
         [0.9104, 0.0308, 0.2843, 0.5979],
         [0.2447, 0.4871, 0.0436, 0.1283]],

        [[0.6814, 0.1857, 0.6835, 0.4018],
         [0.2664, 0.0833, 0.3682, 0.2783],
         [0.2392, 0.1751, 0.1813, 0.5751]]])

## Tensor datatypes

Tensors in PyTorch by default store data in float_32 dtype unless explicitly initialized ie. .rand(), .zeroes(), .ones(), and .rand_like() return a tensor of dtype float_32. The major error points while coding with PyTorch are:
*  selection of datatypes 
*  wrong tensor dimensions 
*  tensors not on the right device

While initializing tensors we can pass params like:
*  dtype: datatype of tensor (torch.floa32 / torch.float64)
*  device: which device is the tensor on or associated with GPU or CPU
*  requires_grad: if PyTorch should track the gradients of the tensor while it is computed on

In [12]:
float_32 = torch.tensor([3.0,6.0,9.0], dtype=None, device=None, requires_grad=False)
new = torch.rand_like(input=float_32, dtype=torch.float64)
new
float_32
float_32.dtype

tensor([0.7637, 0.1203, 0.8885], dtype=torch.float64)

tensor([3., 6., 9.])

torch.float32

### .dtype 

is the property of tensor that represents the type of data stored in the tensor

### Typecasting

Explicit typecasting is done by .type() method

In [31]:
float_16 = float_32.type(torch.float16)
float_16.dtype

torch.float16

Here we see that the result is implicitly typecasted to be float32

> Note that the .type() method returns the typecasted tensor and so the returned tensor has to be assigned to some other new tensor or the original tensor

In [14]:
result = float_16 * float_32
result.dtype

torch.float32

Tensor attributes can be fetched as:
*  datatype: tensor.dtype
*  device: tensor.device
*  shape: tensor.shape | can also use tensor.size(). While shape is a property, size is a method

In [15]:
result.dtype
result.shape
result.size()
result.device

torch.float32

torch.Size([3])

torch.Size([3])

device(type='cpu')

.to() method can change the tensor attributes like device and dtype

In [16]:
# result.to(device="cuda", dtype=torch.float64)

## Tensor Manipulation

Tensors can be operated on as:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [17]:
test = torch.tensor([[[1,2,3],[4,5,6]]], dtype=torch.long)

# Addition
test + 7

# Multiplication
new_test = test * 4

# Subtraction
test - 12

# Division
test / 5

tensor([[[ 8,  9, 10],
         [11, 12, 13]]])

tensor([[[-11, -10,  -9],
         [ -8,  -7,  -6]]])

tensor([[[0.2000, 0.4000, 0.6000],
         [0.8000, 1.0000, 1.2000]]])

Tensors are multiplied in two ways:

* Multiplication with a scalar (*)
* Matrix Multiplication (@)


In [18]:
# Scalar multiplication
print(f"{test} * {new_test} = {test * new_test}")

# Matrix multiplication
# torch.matmul(test, new_test)

d1 = torch.tensor([[1,2,3],[4,5,6]])
d2 = torch.tensor([[1,2],[3,4]])
try:
  torch.matmul(d1,d2)
except Exception as exp:
  print(exp)

tensor([[[1, 2, 3],
         [4, 5, 6]]]) * tensor([[[ 4,  8, 12],
         [16, 20, 24]]]) = tensor([[[  4,  16,  36],
         [ 64, 100, 144]]])
mat1 and mat2 shapes cannot be multiplied (2x3 and 2x2)


One of the most frequent errors faced while working with neural networks and writing deep learning code is the size mismatch of tensors that are being multiplied. 

The two important rules followed are:

1. The inner dimensions must match:
  * `(3,2) @ (2,3)` will work
  * `(3,2) @ (3,2)` won't work
  * `(2,3) @ (3,2)` will work
  
2. The resulting matrix will have the shape of outer dimensions

>Note: inner dimensions for (5,7) and (4,6) are (5,4) and outer dimensions are (7,6)

## Tensor Aggregation

We can find the max, min, sum, avg of a tensor by using tensor aggregation methods.

In [53]:
random_tensor = torch.rand([3,3,3]) * 100
random_tensor = random_tensor.type(torch.int16) # Refer to the note in explicit typecasting section
random_tensor
random_tensor.dtype

tensor([[[10, 64, 40],
         [93, 34, 57],
         [35, 73, 30]],

        [[74, 98, 27],
         [32, 72, 99],
         [24, 61, 50]],

        [[ 7, 53, 65],
         [77, 16,  0],
         [39, 62, 78]]], dtype=torch.int16)

torch.int16

In [56]:
# Finding min
random_tensor.min()

# Finding max
random_tensor.max()

# Finding mean
try:
  random_tensor.mean()
except RuntimeError:
  print("Tensor must be of dtype float or complex and not integer")

# Finding sum
random_tensor.sum()

# Finding the positional min
random_tensor.argmin()

# Finding the positional max
random_tensor.argmax()

tensor(0, dtype=torch.int16)

tensor(99, dtype=torch.int16)

Tensor must be of dtype float or complex and not integer


tensor(1370)

tensor(23)

tensor(14)

> Note that the .argmin() and .argmax() methods return the position of the min and max value assuming that the tensor is one dimensional ie. In a 3x3x3 tensor if the element of index `[1][2][1]` is min then the value returned by the method will be 16. We can see that the reasoning behind the result is that position is counted as 8 when we reach `[0][2][2]` from `[0][0][0]` and continue as 9 for `[1][0][0]`